film_review/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from main import views

urlpatterns = [
    path('', views.index, name='home'),
    path('admin/', admin.site.urls),
    path('logout/', views.logout_user, name="logout"),
    path('delete_comment/<int:pk>', views.delete_comment, name="delete_comment"),
    path('films/', views.films, name="films"),
    path('login/', views.login_user, name="login"),
    path("random_film/", views.random_film, name="random_film"),
    path("registration/", views.registration, name="registration"),
    path('accounts/<int:pk>/', views.profile, name='profile'),
    path('film/<int:pk>/', views.film, name='film'),
    path('find_random_film/', views.find_random_film, name='find_random_film'),
    path('select2/', include('django_select2.urls')),
]

main/models.py
from django.db import models
from django.contrib import admin
from django.utils.translation import gettext_lazy
from django.core.validators import (MinValueValidator,  MaxValueValidator)
import datetime
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.shortcuts import reverse


class Director(models.Model):
    name = models.CharField(unique=True, max_length=50, verbose_name="Имя", blank=True, null=True)

    class Meta:
        verbose_name = 'Режиссёр'
        verbose_name_plural = 'Режиссёры'

    def __str__(self):
        return self.name


class Actor(models.Model):
    name = models.CharField(unique=True, max_length=50, verbose_name="Имя", blank=True, null=True)
    img = models.CharField(verbose_name="Изображение", max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = 'Актёр'
        verbose_name_plural = 'Актёры'

    def __str__(self):
        return self.name

 
class User(AbstractUser):
    nick = models.CharField(max_length=50, verbose_name="Никнейм")
    email = models.EmailField(gettext_lazy('email address'), unique=True)
    img = models.CharField(verbose_name="Изображение", max_length=100, blank=True, null=True)
    description = models.TextField(verbose_name="Обо мне", null=True, blank=True)
    is_moderator = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email


class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Жанр")

    class Meta:
        ordering = ('-pk',)
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self):
        return self.name

# Create your models here.
class Film(models.Model):
    RatingValidator = [MinValueValidator(0), MaxValueValidator(10)]

    title = models.CharField(verbose_name="Название", max_length=100, null=True, blank=True)
    img = models.CharField(verbose_name="Изображение", max_length=100, null=True, blank=True)
    box_office = models.CharField(verbose_name="Кассовые сборы", max_length=100, null=True, blank=True)
    budget = models.CharField(verbose_name="Бюджет", max_length=100, null=True, blank=True)
    year = models.PositiveIntegerField(verbose_name="Год", null=True, blank=True)
    description = models.TextField(verbose_name="Описание", blank=True, null=True)
    rating = models.FloatField(verbose_name="Рейтинг", blank=True, null=True, validators=RatingValidator)
    genres = models.ManyToManyField(Genre, verbose_name="Жанры")
    actors = models.ManyToManyField(Actor, verbose_name="Актёры")
    directors = models.ManyToManyField(Director, verbose_name="Режиссёры")

    class Meta:
        ordering = ('-pk',)
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'

    def __unicode__(self):
        return self.title
 
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('film', kwargs={'pk': self.pk})


class Comment(models.Model):
    film = models.ForeignKey(Film, blank=True, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    title = models.CharField(verbose_name="Тема", max_length=100, null=True, blank=True)
    content = models.TextField(verbose_name="Рецензия", blank=True, null=True)
    pub_date = models.DateTimeField(verbose_name="Дата комментария", default=timezone.now)

    class Meta:
        ordering = ('-pk',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.title

    def get_edit_url(self):
        return reverse('create_or_update_comment', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('delete_comment', kwargs={'pk': self.pk})

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation
from django.contrib.auth.forms import AuthenticationForm
from main.models import User, Comment

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'autofocus': True}), label='Email')


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'nick', 'description')

class CommentForm(forms.ModelForm):

    class Meta:
        model  = Comment
        fields = ('title', 'content')

main/views.py
import uuid

from .filters import FilmFilter
from .models import Film, User, Comment
from django.contrib import auth
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from main.forms import CommentForm
from main.forms import LoginForm
from main.forms import RegistrationForm
from main.models import Comment
from main.models import User
from main.permissions import anonymous_only
from django.http import JsonResponse
from django.core import serializers
import json


def index(request):
    return render(request, "main/index.html", {'users': len(User.objects.all()),'reviews':len(Comment.objects.all()), 'films': Film.objects.all()})


def random_film(request):
    return render(request, "main/random_film.html", {'film': Film.objects.order_by('?').first()})


def logout_user(request):
    logout(request)
    return redirect('/')


def films(request):
    fltr = FilmFilter(request.GET, request=request, queryset=Film.objects.all())

    page = request.GET.get('page', 1)
    paginator = Paginator(fltr.qs, 8)
    paginated_films = paginator.get_page(page)

    return render(request, "main/films.html", {'paginated_films': paginated_films, 'filter': fltr})


def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    red = redirect(request.META.get('HTTP_REFERER', '/'))
    if comment.user != request.user:
        return red
    comment.delete()
    return red


def film(request, pk):
    film = get_object_or_404(Film, id=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        form.instance.user = request.user
        form.instance.film = film
        form.save()
        return redirect(film)
    return render(request, 'main/film.html', {'film': film, "form": form})


@anonymous_only
def login_user(request):
    login_form = LoginForm()
    if request.method == 'POST':
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('home')
            else:
                login_form.add_error(
                    None, "Пользователь с таким логином или паролем не существует")
                return render(request, 'main/login.html', {'login_form': login_form})

    return render(request, 'main/login.html', {'login_form': login_form})


@anonymous_only
def registration(request):
    edit_form = RegistrationForm()
    if request.method == 'POST':
        edit_form = RegistrationForm(data=request.POST)
        if edit_form.is_valid():
            user = edit_form.save(commit=False)
            user.username = str(uuid.uuid4().int)[:10]
            user.save()
            return redirect('login')

    return render(request, 'main/registration.html', {'edit_form': edit_form})


def profile(request, pk):
    user = get_object_or_404(User, id=pk)
    return render(request, 'main/profile.html', {'user': user})

def find_random_film(request):
    print("great!")
    film = Film.objects.order_by('?').first()
    film_data = serializers.serialize('json',[film], ensure_ascii=False)[1:-1]
    return JsonResponse({"film":film_data, "film_url":film.get_absolute_url()}, safe=False) 

main/templates/main/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load staticfiles %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#044076">
    <link rel="stylesheet" href="{% static 'css/base.css'%}">
    <link rel="shortcut icon" href="{% static 'img/video-camera.ico' %}" type="image/x-icon" />
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <title>film-review.ru</title>
    {{filter.form.media.css}}
</head>

<body>
    <!--хедер-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-3">
        <a class="navbar-brand" href="{% url 'home' %}">
            <h5>FR.ru</h5>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between navbar" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'films' %}">
                    <h5>Фильмы</h5>
                </a>
                <a class="nav-item nav-link" href="{% url 'random_film' %}">
                    <h5>Генератор</h5>
                </a>
                {% if request.user.is_authenticated %}
                    <a class="nav-item nav-link" href="/accounts/{{ request.user.id }}">
                        <h5>Мой профиль</h5>
                    </a>
                {% endif %}                
            </div>
            <div>
                {% if request.user.is_authenticated %}
                <a class="nav-item nav-link m-0 p-0" href="{% url 'logout' %}">
                    <h5>{{user.nick}}</h5>
                </a>
                {% else %}
                <a class="nav-item nav-link m-0 p-0" href="{% url 'login' %}">
                    <h5>Войти</h5>
                </a>
                {% endif %}
            </div>
        </div>
    </nav>
    <!---->
    <div class="row no-gutters">
        <div class="row no-gutters col-xl-11 col-lg-11 col-md-10 col-sm-10 col-10 mx-auto main_container my-5" >
            {% block main_content %}
            {% endblock %}
        </div>
    </div>
{{filter.form.media.js}}

</body>
</html>

main/templates/main/film.html
{% extends 'main/base.html' %}
{% block main_content%}
{% load bootstrap4%}
    <div class="col-12 row no-gutters">
        <h2 class="col-12">{{film.title}}</h2>
        <div class="col-12 row no-gutters">
            <div class="col-md-6 col-12">
                <img src='{{film.img}}'>
            </div>
            <div class="col-md-6 col-12">
                <h4>Год премьеры: {{film.year}}</h4>
                <h4>Жанр:
                 {% for genre in film.genres.all %}
                        {{genre}}
                 {% endfor %}
                </h4>
                <h4>Описание: </h4><p>{{film.description}}</p>
                <h5>Сборы: {{film.box_office}}</h5>
                <h5>Бюджет: {{film.budget}}</h5>
                <h5>Режиссёр: 
                    {% for director in film.directors.all %}
                        {{director}}
                    {% endfor %}
                </h5>
                <h6>Актёры: 
                    {% for actor in film.actors.all %}
                        {{actor}}
                    {% endfor %}
                </h6>
            </div>
        </div>
        {% if request.user.is_authenticated %}
        <h5 class="col-12 text-center mt-5 "><span class="write text-white">Напишите</span> свою рецензию</h5>
        {% else %}
        <h5 class="col-12 text-center mt-5 "><a href="{% url 'login' %}" style="text-decoration:none;"><span class="write text-white">Войдите</span></a>, чтобы написать рецензию</h5>
        {% endif %}

        {% if request.user.is_authenticated %}
        <form action="" method="post" id = "comment_form" class="col-12 row no-gutters mx-auto">
        {% if form.errors %}
            <p class="col-12">Пожалуйста, исправьте ошибки ниже.</p>
        {% endif %}
        <div class="col-12 row no-gutters comment">
            <div class="row no-gutters col-md-6 col-10 mx-auto">
                {% csrf_token %}
                {% bootstrap_form form layout='horizonal' form_group_class='label_login col-12 mb-2' label_class='col-12 ' field_class='col-12' %}
            </div>
            <div class="col-12 row no-gutters">
                <button type="submit" class="col-md-2 col-4 my-3 mx-auto btn btn-dark">Отправить</button>
            </div>
        </div>
        </form>
        {% endif %}
            {%if film.comment_set.all %}
                {%for comment in film.comment_set.all %}
                <div class="row no-gutters col-12 mb-5">
                    <div class="col-md-6 col-10 mx-auto block_of_comment px-2 py-3">
                       <h4> {{comment.title}}</h4>
                       <h5>{{comment.content}}</h5>
                       <div class="d-flex justify-content-between">
                       <p class="text-right">{{comment.pub_date}}</p>
                       {% if comment.user == request.user %}
                        <a href="{{comment.get_delete_url}}" class="mt-2">
                            <span style="font-size:60%;" class="text-white">удалить</span>
                        </a>
                       {% endif %}
                    </div>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
    </div>
<script type="text/javascript">
$("#id_title, #id_content").val('')

$(".write").click(function() {
    $(".comment").toggle("slow", function() {
        // Animation complete.
    });
});
</script>
{%endblock%}

main/templates/main/film_card.html
<div class="col-10 mx-auto movie_card card" id="film_card_url" onclick="location.href = '{{film.get_absolute_url}}'">
        <img id="film_card_img" src = "{{film.img}}" class="card-img-top mx-auto">
        <div class="card-body">
            <h5 class="card-title" id="film_card_title">{{film.title}}</h5>
            <p class="card-text">
                Жанр: 
                <span id="film_card_genre">
                    {% for genre in film.genres.all %}
                        {{genre}}
                        {% if forloop.counter != film.genres.all|length %}
                            ,
                        {% endif %}
                {% endfor %}
            </p>
            <p class="card-text">
                Сборы: 
                <span id="film_card_box">
                    {% if film.box_office %}
                        {{ film.box_office }}
                    {% endif %}
                </span>
            </p>
            <p class="card-text">
                Бюджет: 
                <span id="film_card_budget">
                    {% if film.budget %}
                        {{film.budget}}
                    {% endif %}
            </p>
            <p class="card-text" id="film_card_year">{{film.year}}</p>
        </div>
</div>

main/templates/main/films.html
{% extends 'main/base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load staticfiles %}
{% block main_content %}

<form action="" method="GET" class="row no-gutters col-3">
    <div class="container">
       {% bootstrap_field filter.form.keywords bound_css_class="col-12 f_input" label_class="col-12 h_filter m-0 p-0 mb-1" %}
       {% bootstrap_field filter.form.order bound_css_class="col-12 f_input" label_class="col-12 h_filter m-0 p-0 mb-1" %}
       {% bootstrap_field filter.form.genres bound_css_class="col-12 f_input" label_class="col-12 h_filter m-0 p-0 mb-1" %}
       {% bootstrap_field filter.form.year bound_css_class="col-12 f_input" label_class="col-12 h_filter m-0 p-0 mb-1" %}
    <div class="col-12">
    <button class="btn btn-dark mx-auto" type="submit">Поиск</button>
    </div>
    </div>

</form>
<div class="col-9 row no-gutters" >
    <div class="mt-3 col-12 row no-gutters">
        {% for film in paginated_films %}
        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6 col-12 row no-gutters mb-3 d-flex align-items-content">
            {% include "main/film_card.html" with film=film%}
        </div>
        {% endfor %}
    </div>
</div>

<div class="col-12 my-3 d-flex justify-content-center">
    <div>
        {% include 'main/paginator.html' with paginated=paginated_films %}
    </div>
</div>
</div>

<style>
.filter-label {
    font-weight: bold;
}

input:not([type='checkbox']),
select,
.select2 {
    width: 100% !important;
}

.h_filter {
    font-size: 120%;
    color: white;
}

.f_input input,
.f_input select {
    border-radius: 1vh;
    font-size: 110%;
    background: #E6E6E6 !important;
}

.f_input span,
.select2-results__options {
    background: #E6E6E6 !important;
}

span.select2-selection.select2-selection--multiple {
    border: 1px solid #ced4da;
}

.select2 {
    border-radius: 1vh !important;
}
</style>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load staticfiles %}
{% block main_content %}
<div class="row no-gutters">
    <div class="row no-gutters my-5 col-sm-3 d-none d-sm-flex justify-content-center align-items-center">
        <div class="statistic">
            <h5>Фильмов <span id="films">0</span></h5>
            <h5>Рецензий <span id="rews">0</span></h5>
            <h5>Пользователей <span id="users">0</span></h5>
        </div>
    </div>
    <div class="col-sm-9 my-5 d-flex justify-content-strech">
        <div class="main_logo_text d-flex justify-content-center align-items-center">
            <h3 class="px-5">FR.ru - сервис для выражения Вашего мнения о новинках и классике</h3>
        </div>
    </div>
    <div class="mt-5 col-12 row no-gutters">
        {%for film in films|slice:"8"%}
        <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 col-12 row no-gutters mb-3 d-flex align-items-content">
            {% include "main/film_card.html" with film=film%}
        </div>
        {%endfor%}
    </div>
</div>
<script src="{% static 'js/timer.js'%}"></script>
<script type="text/javascript">
jQuery(function($) {
    $('#films').countTo({
        from: 0,
        to: '{{films|length}}',
        speed: 1500,
        refreshInterval: 50,
        onComplete: function(value) {
            console.debug(this);
        }
    });
});

jQuery(function($) {
    $('#rews').countTo({
        from: 0,
        to: '{{reviews}}',
        speed: 1500,
        refreshInterval: 50,
        onComplete: function(value) {
            console.debug(this);
        }
    });
});

jQuery(function($) {
    $('#users').countTo({
        from: 0,
        to: '{{users}}',
        speed: 1500,
        refreshInterval: 50,
        onComplete: function(value) {
            console.debug(this);
        }
    });
});
</script>
{% endblock %}

main/templates/main/login.html
{% extends 'main/base.html' %}
{% block main_content%}
{% load bootstrap4 %}
    <div class="col-12 row no-gutters">
        <h2 class="col-12 text-center my-5">Вход на сайт</h2>
        <form action="" method="post" class="form col-xl-6 col-lg-8 col-10 mx-auto">
            {% csrf_token %}
            {% bootstrap_form login_form layout='horizontal' form_group_class='label_login py-4' label_class='col-4 pl-4' field_class='col-7 mx-auto' %}
            <div class="col-12 d-flex justify-content-around my-5 px-4 py-2">
                <button type="submit" class="btn btn-dark">Войти</button>
                <button type="button" onclick = "location.href='{% url 'registration' %}'" class="btn btn-dark">Зарегистрироваться</button>
            </div>  
            
        </form>
    </div>
<script type="text/javascript">
    $('input').attr('autocomplete','off');
</script>
{%endblock%}

main/templates/main/paginator.html
{% if paginated.has_other_pages %}
  <ul class="pagination">
    {% if paginated.has_previous %}
      <li class="mx-1 d-flex justify-content-center align-items-center"><a href="?page={{ paginated.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="mx-1 disabled d-flex justify-content-center align-items-center"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginated.paginator.page_range %}
      {% if paginated.number == i %}
        <li class="mx-1 active d-flex justify-content-center align-items-center"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li class="mx-1 d-flex justify-content-center align-items-center"><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if paginated.has_next %}
      <li class="mx-1 d-flex justify-content-center align-items-center"><a href="?page={{ paginated.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="mx-1 disabled d-flex justify-content-center align-items-center"><span>&raquo;</span></li>
    {% endif %}
  </ul>

<style>
    .pagination li{
        width: 50px;
        height: 50px;
        border:1px solid white;
        border-radius:50%;
        font-size: 120%;
        background: rgba(0,0,0,0.5);
        color:darkgrey;
    }
    .pagination li:hover{
        background: rgba(0,0,0,0.8);
    }
    .pagination li a, li a:hover{
        color:white;
        text-decoration: none;
    }
</style>
{% endif %}

main/templates/main/profile.html
{% extends 'main/base.html' %}
{% block main_content%}
{% load bootstrap4%}
    <div class="col-12 row no-gutters">
        <div class="col-md-12 px-5 mb-3">
            <h2 class="text-center">{{user.first_name}} {{user.last_name}}</h2>
            <h5 class="mt-5">Никнейм на сайте: <span>{{user.nick}}</span></h5>
            {% if user.description %}
	            <h5 class="mt-5 text-center">Обо мне:</h5>
	            <h5>{{user.description}}</h5>
            {% endif %}
        </div>
        <div class="col-md-12">
            <h3 class="text-center">Мои рецензии</h3>
            {%if user.comment_set.all %}
            	{%for comment in user.comment_set.all %}
                <div class="row no-gutters col-12 mb-5">
                    <div class="col-md-6 col-10 mx-auto block_of_comment px-2 py-3">
                       <h4> {{comment.title}}</h4>
                       <h5>{{comment.content}}</h5>
                       <div class="d-flex justify-content-between">
                       <p class="text-right">{{comment.pub_date}}</p>
                       {% if comment.user == request.user %}
                        <a href="{{comment.get_delete_url}}" class="mt-2">
                            <span style="font-size:60%;" class="text-white">удалить</span>
                        </a>
                       {% endif %}

                    </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
            <h5 class="mt-5">Нет ни одной рецензии - напишите их</h5>
			{% endif %}
            <!-- Цикл сюда -->
        </div>
    </div>
{%endblock%}

main/templates/main/random_film.html
{% extends 'main/base.html' %}
{% block main_content%}
<div class="row no-gutters py-5">
    <div class="col-12 row no-gutters">
        <h2 class="col-6 mx-auto mb-4 text-center">Если вы не знаете, какой фильм посмотреть сегодня вечером - воспользуйтесь генератором</h2>
    </div>
    <div class="col-6 d-flex justify-content-center align-items-center">
        <button type="button" class="btn btn-dark" id="find_film">Случайный фильм</button>
    </div>
    <div class="row no-gutters col-4 mx-auto">
        <div id="app">
            <a :href="[[get_absolute_url]]">
                <div class="col-10 mx-auto movie_card card" id="film_card_url">
                    <img id="film_card_img" :src=[[image]] class="card-img-top mx-auto">
                    <div class="card-body">
                        <h5 class="card-title" id="film_card_title">[[ title ]]</h5>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <style type="text/css">
    .card-img-top {
        width: 60%;
        padding-top: 10%;
    }

    .card p {
        display: none;
    }

    #film_card_title {
        text-align: center;
    }
    </style>
</div>
<script type="text/javascript">
var app = new Vue({
    el: '#app',
    data: {
        title: '{{film.title}}',
        image: '{{film.img}}',
        get_absolute_url: '{{film.get_absolute_url}}'
    },
    delimiters: ['[[', ']]']
})
</script>
<script type="text/javascript">
$("#find_film").click(function() {
    $.get("{% url 'find_random_film' %}", function(data, status) {
        console.log(data.film_url)
        fields = $.parseJSON(data.film).fields
        app.title = fields.title
        app.image = fields.img
        app.get_absolute_url = data.film_url
    })
});
</script>
{%endblock%}

main/templates/main/registration.html
{% extends 'main/base.html' %}
{% block main_content%}
{% load bootstrap4%}
    <div class="col-12 row no-gutters">
        <h2 class="col-12 text-center profile_blue my-5">Регистрация</h2>
        <form action="" method="post" class="form col-xl-6 col-lg-8 col-10 mx-auto">
            {% csrf_token %}
            {% bootstrap_form edit_form layout='horizontal' form_group_class='row no-gutters custom_hr py-4' label_class='col-4 profile_blue pl-4 label_font' field_class='col-7 mx-auto' %}
            <div class="col-12 d-flex justify-content-center">
                <button type="submit" class="btn btn_blue my-5 px-4 py-2">Зарегестрироваться</button>
            </div>
        </form>
    </div>
{%endblock%}